INSERT INTO `products` (`name`, `price`) VALUES
    ('Arroz', 2.50),
    ('Feijão', 4.00),
    ('Óleo de soja', 7.90),
    ('Sal refinado', 1.80),
    ('Açúcar refinado', 3.50),
    ('Açúcar cristalizada', 3.80),
    ('Café em pó', 8.20),
    ('Farinha de trigo', 2.90),
    ('Fubá', 1.50),
    ('Macarrão espaguete', 3.20),
    ('Fermento em pó', 2.00),
    ('Biscoito de maisena', 4.50),
    ('Aveia em flocos', 3.80),
    ('Cereal matinal', 6.90),
    ('Farofa pronta', 5.20),
    ('Farinha de mandioca', 2.30),
    ('Milho de pipoca', 1.70),
    ('Bolacha recheada', 2.80),
    ('Grão de bico', 4.20),
    ('Lentilha', 3.60),
    ('Amendoim torrado e salgado', 5.90),
    ('Chocolate em pó', 6.50),
    ('Leite em pó integral', 9.80),
    ('Creme de leite em lata', 3.20),
    ('Molho de tomate pronto', 2.40),
    ('Azeitona verde em conserva', 4.30),
    ('Milho verde em conserva', 3.10),
    ('Ervilha em conserva', 2.80),
    ('Extrato de tomate', 2.60),
    ('Polvilho doce', 2.10),
    ('Polvilho azedo', 2.20),
    ('Coco ralado desidratado', 3.50),
    ('Gelatina em pó', 1.90),
    ('Chá preto', 4.30),
    ('Chá verde', 4.80),
    ('Sagu', 1.20),
    ('Farinha de rosca', 2.10),
    ('Cuscuz de milho', 2.40),
    ('Leite condensado', 3.70),
    ('Leite de coco', 4.20),
    ('Caldo de galinha em cubos', 1.50),
    ('Caldo de carne em cubos', 1.50),
    ('Vinagre de álcool', 2.00),
    ('Molho shoyu', 5.60),
    ('Açúcar mascavo', 4.00),
    ('Fermento biológico seco', 3.20),
    ('Vinagre balsâmico', 7.90),
    ('Molho inglês', 6.80),
    ('Mostarda', 3.50),
    ('Catchup', 3.20),
    ('Maionese', 4.50),
    ('Molho de pimenta', 4.70),
    ('Mel', 9.50),
    ('Geleia de morango', 5.20),
    ('Geleia de damasco', 5.20),
    ('Geleia de framboesa', 5.20),
    ('Bolinho de chuva mix', 3.80),
    ('Leite condensado diet', 4.00),
    ('Granola', 6.90),
    ('Pão de queijo mix', 3.50),
    ('Fermento em pó químico', 2.00),
    ('Fécula de batata', 1.90),
    ('Pimenta do reino em pó', 5.00),
    ('Canela em pó', 3.50),
    ('Extrato de baunilha', 7.50),
    ('Semente de linhaça', 3.80),
    ('Castanha de caju', 8.90),
    ('Castanha-do-pará', 9.50),
    ('Amendoim sem casca', 6.20),
    ('Cereal de arroz', 4.50),
    ('Cereal de milho', 4.00),
    ('Macarrão instantâneo', 2.80);

